# Generated by Django 5.2.4 on 2025-09-15 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Первый день месяца', verbose_name='Месяц оплаты')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма к оплате')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Оплаченная сумма')),
                ('status', models.CharField(choices=[('paid', 'Оплачено'), ('unpaid', 'Не оплачено'), ('partial', 'Частично оплачено')], default='unpaid', max_length=10, verbose_name='Статус оплаты')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки об оплате', verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='athletes.athlete', verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['-month', 'athlete__last_name'],
                'unique_together': {('athlete', 'month')},
            },
        ),
    ]
