# Generated by Django 5.2.4 on 2025-07-30 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0002_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Первый день месяца', verbose_name='Месяц оплаты')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='athletes.athlete', verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'Запись оплаты',
                'verbose_name_plural': 'Записи оплаты',
                'ordering': ['-month', 'athlete__last_name'],
                'unique_together': {('athlete', 'month')},
            },
        ),
    ]
