# Generated by Django 5.2.4 on 2025-08-06 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'db_table': 'document_type',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('object_id', models.BigIntegerField(verbose_name='ID объекта')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Временная метка')),
                ('details', models.TextField(default='', verbose_name='Детали')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Записи аудита',
                'db_table': 'audit_record',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('photo', models.TextField(default='', verbose_name='Фото')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивирован')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования')),
                ('phone', models.CharField(max_length=255, unique=True, verbose_name='Телефон')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='Архивирован кем')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('photo', models.TextField(default='', verbose_name='Фото')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивирован')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='Архивирован кем')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
                'db_table': 'parent',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=255, verbose_name='Файл')),
                ('file_type', models.CharField(max_length=255, verbose_name='Тип файла')),
                ('file_size', models.IntegerField(verbose_name='Размер файла')),
                ('object_id', models.BigIntegerField(verbose_name='ID объекта')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_private', models.BooleanField(default=False, verbose_name='Приватный')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивирован')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип контента')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загружен кем')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documenttype', verbose_name='Тип документа')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='Архивирован кем')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.TextField(default='', verbose_name='Фото')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивирован')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='Архивирован кем')),
            ],
            options={
                'verbose_name': 'Спортсмен',
                'verbose_name_plural': 'Спортсмены',
                'db_table': 'athlete',
            },
        ),
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('age_min', models.IntegerField(verbose_name='Минимальный возраст')),
                ('age_max', models.IntegerField(default=18, verbose_name='Максимальный возраст')),
                ('max_athletes', models.IntegerField(default=20, verbose_name='Максимум спортсменов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивирована')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traininggroup_archived_by_set', to='core.staff', verbose_name='Архивирована кем')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Тренировочная группа',
                'verbose_name_plural': 'Тренировочные группы',
                'db_table': 'training_group',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
                ('billing_period_start', models.DateField(verbose_name='Начало периода оплаты')),
                ('billing_period_end', models.DateField(verbose_name='Конец периода оплаты')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивирован')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('is_automated', models.BooleanField(verbose_name='Автоматизирован')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('invoice_number', models.CharField(max_length=255, unique=True, verbose_name='Номер счета')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.athlete', verbose_name='Спортсмен')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Плательщик')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paymentmethod', verbose_name='Способ оплаты')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_archived_by_set', to='core.staff', verbose_name='Архивирован кем')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff', verbose_name='Создан кем')),
                ('training_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.traininggroup', verbose_name='Тренировочная группа')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Отменена')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='Отменена кем')),
                ('training_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.traininggroup', verbose_name='Тренировочная группа')),
            ],
            options={
                'verbose_name': 'Тренировочная сессия',
                'verbose_name_plural': 'Тренировочные сессии',
                'db_table': 'training_session',
            },
        ),
        migrations.CreateModel(
            name='AthleteParent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.athlete', verbose_name='Спортсмен')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parent', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Связь спортсмен-родитель',
                'verbose_name_plural': 'Связи спортсмен-родитель',
                'db_table': 'athlete_parent',
                'unique_together': {('athlete', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('training_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.traininggroup', verbose_name='Тренировочная группа')),
            ],
            options={
                'verbose_name': 'Расписание группы',
                'verbose_name_plural': 'Расписания групп',
                'db_table': 'group_schedule',
                'unique_together': {('training_group', 'weekday', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='AthleteTrainingGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.athlete', verbose_name='Спортсмен')),
                ('training_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.traininggroup', verbose_name='Тренировочная группа')),
            ],
            options={
                'verbose_name': 'Спортсмен в группе',
                'verbose_name_plural': 'Спортсмены в группах',
                'db_table': 'athlete_training_group',
                'unique_together': {('athlete', 'training_group')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('was_present', models.BooleanField(verbose_name='Присутствовал')),
                ('marked_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отметки')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.athlete', verbose_name='Спортсмен')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff', verbose_name='Отметил')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainingsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Запись посещаемости',
                'verbose_name_plural': 'Записи посещаемости',
                'db_table': 'attendance_record',
                'unique_together': {('athlete', 'session')},
            },
        ),
    ]
