# Generated by Django 5.2.4 on 2025-08-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('trainer', 'Тренер'), ('assistant_trainer', 'Помощник тренера'), ('admin', 'Администратор'), ('accountant', 'Бухгалтер'), ('manager', 'Менеджер'), ('other', 'Другой')], default='trainer', max_length=50, verbose_name='Роль'),
        ),
    ]
