# Generated by Django 5.2.4 on 2025-08-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='custom_role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кастомная роль'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('trainer', 'Тренер'), ('assistant_trainer', 'Помощник тренера'), ('admin', 'Администратор'), ('accountant', 'Бухгалтер'), ('manager', 'Менеджер'), ('other', 'Другой (кастомная роль)')], default='other', max_length=50, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='CustomStaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название роли')),
                ('display_name', models.CharField(max_length=150, verbose_name='Отображаемое название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Допуски')),
            ],
            options={
                'verbose_name': 'Кастомная роль',
                'verbose_name_plural': 'Кастомные роли',
                'db_table': 'custom_staff_role',
            },
        ),
    ]
