# Generated by Django 5.2.4 on 2025-08-07 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_staff_custom_role_alter_staff_role_customstaffrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininggroup',
            name='staff',
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customstaffrole', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('accountant', 'Бухгалтер'), ('cleaner', 'Уборщица'), ('security', 'Охрана'), ('doctor', 'Врач'), ('psychologist', 'Психолог'), ('manager', 'Менеджер'), ('other', 'Другой')], default='other', max_length=50, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='Специализация')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Опыт работы (лет)')),
                ('certification', models.TextField(blank=True, verbose_name='Сертификация')),
                ('photo', models.TextField(default='', verbose_name='Фото')),
                ('phone', models.CharField(max_length=255, unique=True, verbose_name='Телефон')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивирован')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='Архивирован кем')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
                'db_table': 'trainer',
            },
        ),
        migrations.AddField(
            model_name='traininggroup',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trainer', verbose_name='Тренер'),
        ),
    ]
