# Generated by Django 5.2.4 on 2025-08-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_traininggroup_staff_staff_staff_role_and_more'),
    ]

    operations = [
    ]
