# Generated by Django 5.2.4 on 2025-08-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250807_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staff_role',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='custom_role',
        ),
        migrations.DeleteModel(
            name='CustomStaffRole',
        ),
    ]
