# Generated by Django 5.2.4 on 2025-08-07 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_staff_staff_role_remove_staff_custom_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDraft',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, choices=[('trainer', 'Тренер'), ('parent', 'Родитель'), ('athlete', 'Спортсмен')], max_length=20, null=True, verbose_name='Роль')),
                ('current_step', models.PositiveSmallIntegerField(default=1, verbose_name='Текущий шаг')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_registration_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Кем начато')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_draft', to=settings.AUTH_USER_MODEL, verbose_name='Временный пользователь')),
            ],
            options={
                'verbose_name': 'Черновик регистрации',
                'verbose_name_plural': 'Черновики регистрации',
                'db_table': 'registration_draft',
            },
        ),
    ]
