# Generated by Django 5.2.4 on 2025-08-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_registrationdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdraft',
            name='staff_role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подроль сотрудника'),
        ),
        migrations.AlterField(
            model_name='registrationdraft',
            name='role',
            field=models.CharField(blank=True, choices=[('trainer', 'Тренер'), ('parent', 'Родитель'), ('athlete', 'Спортсмен'), ('staff', 'Сотрудник')], max_length=20, null=True, verbose_name='Роль'),
        ),
    ]
