# Generated by Django 5.2.4 on 2025-08-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_registrationdraft_staff_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='parent',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Телефон'),
        ),
    ]
