# Generated by Django 5.2.4 on 2025-08-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_staff_description_athlete_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='photo',
        ),
    ]
