# Generated by Django 5.2.4 on 2025-08-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_athlete_photo_remove_parent_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='subrole',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подроль'),
        ),
    ]
