# Generated by Django 5.2.4 on 2025-08-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_staff_subrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('accountant', 'Бухгалтер'), ('cleaner', 'Уборщица'), ('security', 'Охрана'), ('doctor', 'Врач'), ('psychologist', 'Психолог'), ('other', 'Другой')], default='other', max_length=50, verbose_name='Роль'),
        ),
    ]
