# Generated by Django 5.2.4 on 2025-08-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='specialization',
        ),
    ]
