# Generated by Django 5.2.4 on 2025-08-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_trainer_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='parent',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('manager', 'Менеджер')], default='manager', max_length=50, verbose_name='Роль'),
        ),
    ]
