# Generated by Django 5.2.4 on 2025-08-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_parent_first_name_parent_last_name_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
