# Generated by Django 5.2.4 on 2025-08-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_trainingsession'),
    ]

    operations = [
        # Добавляем недостающие поля в таблицу attendance_record
        migrations.AddField(
            model_name='attendancerecord',
            name='training_group',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                to='core.traininggroup', 
                verbose_name='Тренировочная группа'
            ),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session_date',
            field=models.DateField(
                verbose_name='Дата тренировки',
                null=True,  # временно nullable для существующих записей
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session_start_time',
            field=models.TimeField(
                verbose_name='Время начала',
                null=True,  # временно nullable для существующих записей
                blank=True
            ),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session_end_time',
            field=models.TimeField(
                verbose_name='Время окончания',
                null=True,  # временно nullable для существующих записей
                blank=True
            ),
        ),
        # Сначала удаляем старый unique_together
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        # Затем добавляем новый unique_together
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('athlete', 'training_group', 'session_date', 'session_start_time')},
        ),
    ]
