# Generated by Django 5.2.4 on 2025-08-10 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20250810_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.athlete', verbose_name='Спортсмен'),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата тренировки')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Отменена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('training_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.traininggroup', verbose_name='Тренировочная группа')),
            ],
            options={
                'verbose_name': 'Тренировочная сессия',
                'verbose_name_plural': 'Тренировочные сессии',
                'db_table': 'training_session',
                'ordering': ['date', 'start_time'],
                'unique_together': {('training_group', 'date', 'start_time')},
            },
        ),
    ]
