# Generated by Django 5.2.4 on 2025-08-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_attendancerecord_athlete_trainingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(
                default=1,  # Временное значение по умолчанию
                on_delete=django.db.models.deletion.CASCADE,
                to='core.trainingsession',
                verbose_name='Сессия'
            ),
            preserve_default=False,
        ),
    ]
