# Generated by Django 5.2.4 on 2025-08-21 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20250821_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='canceled_by',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='core.staff',
                verbose_name='Отменена кем'
            ),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='canceled_at',
            field=models.DateTimeField(
                null=True,
                blank=True,
                verbose_name='Дата отмены'
            ),
        ),
    ]
