# Generated by Django 5.2.4 on 2025-08-21 10:41

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20250821_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                verbose_name='Обновлено',
                default=timezone.now
            ),
            preserve_default=False,
        ),
    ]
