# Generated by Django 5.2.4 on 2025-09-15 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер группы')),
                ('age_min', models.IntegerField(choices=[(6, '6 лет'), (7, '7 лет'), (8, '8 лет'), (9, '9 лет'), (10, '10 лет'), (11, '11 лет'), (12, '12 лет'), (13, '13 лет'), (14, '14 лет'), (15, '15 лет'), (16, '16 лет'), (17, '17 лет'), (18, '18+ лет')], default=6, verbose_name='Минимальный возраст')),
                ('age_max', models.IntegerField(choices=[(6, '6 лет'), (7, '7 лет'), (8, '8 лет'), (9, '9 лет'), (10, '10 лет'), (11, '11 лет'), (12, '12 лет'), (13, '13 лет'), (14, '14 лет'), (15, '15 лет'), (16, '16 лет'), (17, '17 лет'), (18, '18+ лет')], default=18, verbose_name='Максимальный возраст')),
                ('trainer', models.CharField(max_length=100, verbose_name='Тренер')),
                ('days', models.JSONField(default=list, help_text='Список дней недели для занятий', verbose_name='Дни недели')),
                ('time', models.TimeField(verbose_name='Время занятий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная группа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['number'],
            },
        ),
    ]
