# Generated by Django 5.2.4 on 2025-07-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='days_of_week',
            new_name='days',
        ),
        migrations.RemoveField(
            model_name='group',
            name='age_range',
        ),
        migrations.AddField(
            model_name='group',
            name='age_max',
            field=models.IntegerField(choices=[(6, '6 лет'), (7, '7 лет'), (8, '8 лет'), (9, '9 лет'), (10, '10 лет'), (11, '11 лет'), (12, '12 лет'), (13, '13 лет'), (14, '14 лет'), (15, '15 лет'), (16, '16 лет'), (17, '17 лет'), (18, '18+ лет')], default=18, verbose_name='Максимальный возраст'),
        ),
        migrations.AddField(
            model_name='group',
            name='age_min',
            field=models.IntegerField(choices=[(6, '6 лет'), (7, '7 лет'), (8, '8 лет'), (9, '9 лет'), (10, '10 лет'), (11, '11 лет'), (12, '12 лет'), (13, '13 лет'), (14, '14 лет'), (15, '15 лет'), (16, '16 лет'), (17, '17 лет'), (18, '18+ лет')], default=6, verbose_name='Минимальный возраст'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная группа'),
        ),
    ]
