# Generated by Django 5.2.4 on 2025-09-15 07:42

import athletes.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(help_text='Формат: +7-xxx-xxx-xx-xx', max_length=18, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате: +7-xxx-xxx-xx-xx', regex='^\\+7-\\d{3}-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=athletes.models.athlete_photo_path, verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный спортсмен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='groups.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Спортсмен',
                'verbose_name_plural': 'Спортсмены',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('file', models.FileField(upload_to=athletes.models.athlete_document_path, verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF документ'), ('doc', 'Word документ'), ('docx', 'Word документ'), ('jpg', 'Изображение JPG'), ('jpeg', 'Изображение JPEG'), ('png', 'Изображение PNG'), ('other', 'Другой файл')], default='other', max_length=10, verbose_name='Тип файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='athletes.athlete', verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
