# Generated by Django 5.2.4 on 2025-07-30 21:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birth_date', models.DateField(help_text='Формат: ДД.ММ.ГГГГ', verbose_name='Дата рождения')),
                ('phone', models.CharField(help_text='Формат: +7-xxx-xxx-xx-xx', max_length=18, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате: +7-xxx-xxx-xx-xx', regex='^\\+7-\\d{3}-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='athletes/photos/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='groups.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Спортсмен',
                'verbose_name_plural': 'Спортсмены',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AthleteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='athletes/documents/', verbose_name='Файл')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('file_type', models.CharField(choices=[('document', 'Документ'), ('photo', 'Фото'), ('video', 'Видео'), ('other', 'Другое')], default='document', max_length=20, verbose_name='Тип файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='athletes.athlete', verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'Документ спортсмена',
                'verbose_name_plural': 'Документы спортсменов',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
