# Generated by Django 5.2.4 on 2025-07-30 21:51

import athletes.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный спортсмен'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='phone',
            field=models.CharField(help_text='Формат: +7-xxx-xxx-xx-xx', max_length=15, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате: +7-xxx-xxx-xx-xx', regex='^\\+7-\\d{3}-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=athletes.models.athlete_photo_path, verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('file', models.FileField(upload_to=athletes.models.athlete_document_path, verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF документ'), ('doc', 'Word документ'), ('docx', 'Word документ'), ('jpg', 'Изображение JPG'), ('jpeg', 'Изображение JPEG'), ('png', 'Изображение PNG'), ('other', 'Другой файл')], default='other', max_length=10, verbose_name='Тип файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='athletes.athlete', verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='AthleteAttachment',
        ),
    ]
