# Generated by Django 5.2.4 on 2025-07-30 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_alter_athlete_birth_date_alter_athlete_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='phone',
            field=models.CharField(help_text='Формат: +7-xxx-xxx-xx-xx', max_length=18, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате: +7-xxx-xxx-xx-xx', regex='^\\+7-\\d{3}-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
    ]
