"""
Django settings for cska_django_supabase project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

from dotenv import load_dotenv  # для загрузки переменных окружения из .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Явная загрузка .env из корня проекта (Windows/UTF-8 BOM совместимость)
load_dotenv(dotenv_path=BASE_DIR / '.env', override=False)  # загружаем один раз до чтения переменных


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-key-change-in-production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

# Настройки хостов
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0').split(',')


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # должно быть первым в списке
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',  # Основное приложение с моделями (содержит кастомные фильтры)
    'documents_ui',  # Группа Документы (только заголовок)
    'payments_ui',   # Группа Оплата (только заголовок)
    'athletes',  # Спортсмены
    'attendance',  # Посещаемость
    'groups',  # Группы
    'payments',  # Платежи
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # CLEANUP: enable per-request timezone handling (default activation)
    'django.middleware.timezone.TimeZoneMiddleware',
    # CLEANUP: activate timezone from session if provided
    'core.middleware.SessionTimeZoneMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.RegistrationDraftCleanupMiddleware',
]

ROOT_URLCONF = 'cska_django_supabase.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cska_django_supabase.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration - поддержка SQLite и PostgreSQL (Supabase)
# 1) Пробуем взять готовый DATABASE_URL
DATABASE_URL = os.environ.get('DATABASE_URL')

# 2) Если нет, собираем из отдельных переменных окружения
if not DATABASE_URL:
    db_host = os.environ.get('DB_HOST')
    db_port = os.environ.get('DB_PORT', '5432')
    db_name = os.environ.get('DB_NAME')
    db_user = os.environ.get('DB_USER')
    db_password = os.environ.get('DB_PASSWORD')
    db_ssl_mode = os.environ.get('DB_SSL_MODE', 'require')  # для Supabase обычно 'require'

    # Если заданы все компоненты — формируем URL
    if all([db_host, db_name, db_user, db_password]):
        # Формируем стандартный libpq-URL с sslmode
        DATABASE_URL = (
            f"postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}?sslmode={db_ssl_mode}"
        )

if DATABASE_URL:
    # Подключение к Supabase PostgreSQL
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Локальная SQLite база для разработки
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

# CLEANUP: allow overriding default timezone via environment variable for scalability
TIME_ZONE = os.environ.get('TIME_ZONE', 'Europe/Moscow')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files - поддержка локального хранения и Supabase Storage
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Supabase настройки
SUPABASE_URL = os.environ.get('SUPABASE_URL')
SUPABASE_ANON_KEY = os.environ.get('SUPABASE_ANON_KEY')
SUPABASE_SERVICE_KEY = os.environ.get('SUPABASE_SERVICE_KEY')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки аутентификации - только для админки
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/admin/login/'

# Настройки Jazzmin
JAZZMIN_SETTINGS = {
    "site_title": "Sports CRM Admin",
    "site_header": "Sports CRM",
    "site_brand": "Sports CRM",
    "site_logo": None,
    "welcome_sign": "Welcome to Sports CRM Admin Panel",
    "copyright": "Sports CRM © 2025",
    "search_model": ["auth.User", "core.Athlete", "core.Staff", "core.Parent"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Главная", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "📝 Регистрация", "url": "admin:register_step1", "permissions": ["auth.add_user"]},
        {"name": "Спортсмены", "url": "admin:core_athlete_changelist", "permissions": ["core.view_athlete"]},
        {"name": "Тренеры", "url": "admin:core_staff_changelist", "permissions": ["core.view_staff"]},
        {"name": "Группы", "url": "admin:core_traininggroup_changelist", "permissions": ["core.view_traininggroup"]},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core.PaymentMethod": "fas fa-credit-card",
        "core.Staff": "fas fa-chalkboard-teacher",
        "core.Parent": "fas fa-user-friends",
        "core.Athlete": "fas fa-running",
        "core.AthleteParent": "fas fa-link",
        "core.TrainingGroup": "fas fa-users",
        "core.AthleteTrainingGroup": "fas fa-user-plus",
        "core.GroupSchedule": "fas fa-clock",
        "core.TrainingSession": "fas fa-calendar-alt",
        "core.AttendanceRecord": "fas fa-check-circle",
        "core.DocumentType": "fas fa-file-alt",
        "core.Document": "fas fa-file-upload",
        "core.Payment": "fas fa-money-bill-wave",
        "core.AuditRecord": "fas fa-history",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
        "core.Staff": "horizontal_tabs",
        "core.TrainingGroup": "horizontal_tabs",
        "core.Athlete": "horizontal_tabs",
        "core.Parent": "horizontal_tabs",
    },
    "order_with_respect_to": [
        "auth",
        "core",
    ],
    "hide_apps": [
        "athletes",  # Скрываем дублированное приложение - модели в core
        "attendance",  # Скрываем дублированное приложение - модели в core
        "groups",  # Скрываем дублированное приложение - модели в core
        "payments",  # Скрываем дублированное приложение - модели в core
    ],
    # Скрываем модели, которые не нужны в основном меню
    "hide_models": [
        "core.Staff",  # Скрываем персонал
        "core.AttendanceRecord",  # Скрываем записи посещаемости
        "core.TrainingSession",  # Скрываем сессии
        "core.AthleteParent",  # Скрываем связи
        "core.AthleteTrainingGroup",  # Скрываем связи
        "core.GroupSchedule",  # Скрываем расписание
        "core.AuditRecord",  # Скрываем аудит
        "core.RegistrationDraft",  # Скрываем черновики
    ],
    # Переопределяем название и порядок основных моделей
    "models": {
        "core.TrainingGroup": {"name": "1. Тренировочные группы", "icon": "fas fa-users"},
        "core.Trainer": {"name": "2. Тренеры", "icon": "fas fa-chalkboard-teacher"},
        "core.Athlete": {"name": "3. Спортсмены", "icon": "fas fa-running"},
        "core.Parent": {"name": "4. Родители", "icon": "fas fa-user-friends"},
        "core.Document": {"name": "5. Документы", "icon": "fas fa-file-upload"},
        "core.DocumentType": {"name": "6. Типы документов", "icon": "fas fa-file-alt"},
        "core.Payment": {"name": "7. Платежи", "icon": "fas fa-money-bill-wave"},
        "core.PaymentMethod": {"name": "8. Способы оплаты", "icon": "fas fa-credit-card"},
    },

}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-teal",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cosmo",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Для Jazzmin: используем verbose_name «виртуальных» приложений как разделы
JAZZMIN_SETTINGS["order_with_respect_to"] = [
    "auth",
    "documents_ui",   # Документы
    "payments_ui",    # Оплата
    "core",           # Спортивная CRM (модели из core)
]

# Кеширование (локальная память) — ускоряет повторные запросы в админке и журнале
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'sportcrm-local-cache',
        'TIMEOUT': 300,  # 5 минут
    }
}

# Настройки безопасности для разработки - отключаем HTTPS
SECURE_SSL_REDIRECT = False
SECURE_PROXY_SSL_HEADER = None
SECURE_BROWSER_XSS_FILTER = False
SECURE_CONTENT_TYPE_NOSNIFF = False
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_REFERRER_POLICY = None
SECURE_CROSS_ORIGIN_OPENER_POLICY = None
SECURE_FRAME_DENY = False
# Настройки CSRF для разработки
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]
CSRF_COOKIE_SECURE = False  # Только для разработки  
CSRF_COOKIE_HTTPONLY = False  # Для отладки
SESSION_COOKIE_SECURE = False  # Только для разработки