# Generated by Django 5.2.4 on 2025-07-30 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0002_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('was_present', models.BooleanField(default=True, verbose_name='Присутствовал')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='athletes.athlete', verbose_name='Спортсмен')),
            ],
            options={
                'verbose_name': 'Запись посещаемости',
                'verbose_name_plural': 'Записи посещаемости',
                'ordering': ['-date', 'athlete__last_name'],
                'unique_together': {('athlete', 'date')},
            },
        ),
    ]
